NPOI_dotnetcore6MVC/Models/ErrorViewModel.cs
namespace NPOI_dotnetcore6MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NPOI_dotnetcore6MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting.Internal;
using NPOI_dotnetcore6MVC.Models;
using System;
using System.Diagnostics;

namespace NPOI_dotnetcore6MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IHostEnvironment _hostingEnvironment; // 用 DI 加入 Server wwwroot的 根目錄路徑

        public HomeController(ILogger<HomeController> logger, IHostEnvironment hostingEnvironment)
        {
            _logger = logger;
            _hostingEnvironment = hostingEnvironment; // 用 DI 加入 Server wwwroot的 根目錄路徑
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public string HowToUseSession()
        {
            /// 使用 Session
            var personObj = new MySession()
            {
                Name = "New Person In Session"
            };

            HttpContext.Session.SetComplexObjectSession("John Doe", personObj); // 物件寫入 Session 
            var objFromSession = HttpContext.Session.GetComplexObjectSession<MySession>("John Doe"); // 讀取Session的物件

            return objFromSession.Name;
        }

        public class MySession
        {
            public MySession()
            {
                Id = 0;
                Name = "";
            }

            public int Id { get; set; }
            public string Name { get; set; }

        }
    }
}

NPOI_dotnetcore6MVC/Controllers/NPOIController.cs
using Excel_NPOI;
using Microsoft.AspNetCore.Mvc;
using NPOI.SS.UserModel;
using System.Data;

namespace NPOI_dotnetcore6MVC.Controllers
{
    public class NPOIController : Controller
    {
        private readonly IHostEnvironment _hostingEnvironment; // 用 DI 加入 Server wwwroot的 根目錄路徑
        public NPOIController(IHostEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment; // 用 DI 加入 Server wwwroot的 根目錄路徑
        }

        public IActionResult Index()
        {
            // 需要從 nuget 安裝 NPOI， dotnet core 安裝的是這個 https://www.nuget.org/packages/DotNetCore.NPOI
            MyNPOI writer = new MyNPOI(); // 自己組裝方便存取 Excel NPOI 的元件，位置在 NOPOClass.cs
            var destPath = _hostingEnvironment.ContentRootPath + "/wwwroot/Excel/"; // Excel 檔案的根目錄路徑
            var sourcefilename = "活頁簿1.xlsx"; // 宣告來源檔名
            writer.open(destPath + sourcefilename); // 開啟 excel

            var cellPosition = writer.ExcelCoordinateToCellPosition("A1"); // 選擇要寫入哪一格

            // 輸入資料，前面兩個參數 cellPosition.Item1 和 cellPosition.Item2 對應 excel 座標軸，如果不從上面取A1，也可以自己用數字代入
            writer.SetCell(cellPosition.Item1, cellPosition.Item2, "寫入A1的值", CellType.String);


            var cellPosition2 = writer.ExcelCoordinateToCellPosition("D7");
            writer.SetCell(cellPosition2.Item1, cellPosition2.Item2, "D7被後端程式寫入了資料", CellType.String);
            writer.SetCell(8, 5, "這格是F9，SetCell 起點是0，座標8,5，先數縱向座標軸，再數橫向座標軸", CellType.String);

            var savefilename = "活頁簿1_儲存.xlsx"; // 存檔的檔案
            writer.SaveClose(destPath + savefilename); // 儲存

            return View();

        }
    }
}

NPOI_dotnetcore6MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "首頁";
}

<div class="text-center">
    <h1 class="display-4">Welcome 預設起始頁面</h1>
    <p>
        <a href="~/NPOI/Index">使用 NPOI 讀寫 Excel 的範例程式</a>
    </p>
</div>

NPOI_dotnetcore6MVC/Views/NPOI/Index.cshtml
@{
    ViewData["Title"] = "利用NPOI套版更改excel內容";
}

<h1>@ViewData["Title"]</h1>

<ul>
    <li>下面這個檔案，D7是沒有資料的</li>
    <li><a href="~/Excel/活頁簿1.xlsx">基礎Excel檔 可以預先加入底色</a></li>
    <li>下面這個檔案，D7被後端程式寫入了資料</li>
    <li><a href="~/Excel/活頁簿1_儲存.xlsx">程式擷取基礎Excel檔，經過後端運算後轉存的 Excel 檔</a></li>
</ul>

NPOI_dotnetcore6MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NPOI_dotnetcore6MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NPOI_dotnetcore6MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NPOI_dotnetcore6MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NPOI" asp-action="Index">NPOI</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - NPOI_dotnetcore6MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>